# Notebook 01 -- Data Overview

**Thesis:** Content Moderation on TikTok and X -- A Comparative Analysis of DSA Statements of Reasons (2025)  
**Author:** Mohsen Zahedi  

> **Note:** This notebook is pre-run. Outputs were produced on the author's machine. The full dataset (~120 GB) lives at `C:\BA_Data\` and is not included in this repository. To reproduce, point `DATA_ROOT` to your local copy of the parquet files.

---

This notebook introduces the dataset. It covers what DSA Statement of Reasons data is, which platforms are studied, how large the dataset is, and what each column represents.

## 1. What is DSA Statement of Reasons Data?

Under **Article 17 of the EU Digital Services Act (DSA)**, Very Large Online Platforms (VLOPs) must submit a **Statement of Reasons (SoR)** to the [DSA Transparency Database](https://transparency.dsa.ec.europa.eu/) each time they take a content moderation decision.

Each SoR record captures:

| Field | What it records |
|---|---|
| `category` | Which DSA violation category the content falls under |
| `content_type` | What kind of content was moderated (video, account, comment, etc.) |
| `automated_detection` | Whether automated tools detected the violation |
| `automated_decision` | Whether the moderation decision was made automatically |
| `decision_visibility` | How the content's visibility was restricted (removed, labelled, etc.) |
| `application_date` | When the decision was applied |
| `territorial_scope` | Which countries the restriction applies to |

This thesis analyzes SoR data for **TikTok** and **X (formerly Twitter)** for the calendar year **2025**, restricted to decisions covering **Germany (DE)**.

In [1]:
from pathlib import Path

import polars as pl

DATA_ROOT = Path(r"C:\BA_Data")
TIKTOK_FILE = DATA_ROOT / "tiktok_de_2025.parquet"
X_FILE = DATA_ROOT / "x_de_2025.parquet"

## 2. Dataset Scale

The two platforms differ dramatically in reporting volume.

In [2]:
tiktok_rows = pl.scan_parquet(str(TIKTOK_FILE)).select(pl.len()).collect().item()
x_rows = pl.scan_parquet(str(X_FILE)).select(pl.len()).collect().item()

print(f"Platform   {'Rows':>15}")
print("-" * 30)
print(f"TikTok     {tiktok_rows:>15,}")
print(f"X          {x_rows:>15,}")
print("-" * 30)
print(f"Scale ratio TikTok:X = {tiktok_rows / x_rows:,.0f}:1")

Platform              Rows
------------------------------
TikTok         997,688,267
X                  183,321
------------------------------
Scale ratio TikTok:X = 5,442:1

## 3. Schema

Both platforms share the same 10 columns. These are the nine DSA in-scope fields plus `api_version`, which distinguishes submissions made under DSA API v1 (before July 1, 2025) from v2 (from July 1, 2025 onwards). The v1/v2 distinction matters because the `category` vocabulary changed -- this is addressed in Notebook 03.

In [3]:
schema = pl.read_parquet_schema(str(TIKTOK_FILE))
print(f"{'Column':<30} {'Type'}")
print("-" * 50)
for col, dtype in schema.items():
    print(f"{col:<30} {dtype}")

Column                         Type
--------------------------------------------------
uuid                           String
category                       String
content_type                   String
automated_detection            String
automated_decision             String
territorial_scope              String
application_date               Datetime(time_unit='ms', time_zone=None)
platform_name                  String
decision_visibility            String
api_version                    String

## 4. Column Descriptions

| Column | Type | Description |
|---|---|---|
| `uuid` | String | Unique identifier per SoR record |
| `category` | String | DSA violation category as submitted by the platform (raw, not harmonized) |
| `content_type` | String | Type of content moderated: `VIDEO`, `ACCOUNT`, `POST`, etc. |
| `automated_detection` | String | Whether automated tools flagged the content (`true` / `false`) |
| `automated_decision` | String | Whether the final moderation decision was made automatically |
| `territorial_scope` | String | Country codes where the restriction applies (may be multi-country, e.g. `DE,FR,NL`) |
| `application_date` | Datetime | Date the moderation decision was applied (no timezone in raw data) |
| `platform_name` | String | Name of the platform filing the SoR |
| `decision_visibility` | String | How content visibility was restricted (e.g. `REMOVED_CONTENT`, `LABELLED`) |
| `api_version` | String | DSA API version used to submit the SoR (`v1` or `v2`) |

## 5. Sample Rows

### TikTok

In [4]:
pl.scan_parquet(str(TIKTOK_FILE)).head(5).collect()

shape: (5, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ uuid      ┆ category  ┆ content_t ┆ automated ┆ … ┆ applicati ┆ platform_ ┆ decision_ ┆ api_vers │
│ ---       ┆ ---       ┆ ype       ┆ _detectio ┆   ┆ on_date   ┆ name      ┆ visibilit ┆ ion      │
│ str       ┆ str       ┆ ---       ┆ n         ┆   ┆ ---       ┆ ---       ┆ y         ┆ ---      │
│           ┆           ┆ str       ┆ ---       ┆   ┆ datetime[ ┆ str       ┆ ---       ┆ str      │
│           ┆           ┆           ┆ str       ┆   ┆ ms]       ┆           ┆ str       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0b3c3647- ┆ STATEMENT ┆ ["CONTENT ┆ Yes       ┆ … ┆ 2025-01-0 ┆ TikTok    ┆ ["DECISIO ┆ v1       │
│ 9806-419c ┆ _CATEGORY ┆ _TYPE_VID ┆           ┆   ┆ 1         ┆           ┆ N_VISIBIL ┆          │
│ -bd99-de6 ┆ _SCOPE_OF ┆ EO"]      ┆           ┆   ┆ 00:00:00  ┆           ┆ ITY_OTHER ┆          │
│ 6b6…      ┆ _PL…      ┆           ┆           ┆   ┆           ┆           ┆ "]        ┆          │
│ 8415527b- ┆ STATEMENT ┆ ["CONTENT ┆ Yes       ┆ … ┆ 2025-01-0 ┆ TikTok    ┆ ["DECISIO ┆ v1       │
│ 855e-437b ┆ _CATEGORY ┆ _TYPE_VID ┆           ┆   ┆ 1         ┆           ┆ N_VISIBIL ┆          │
│ -a698-4ee ┆ _SCOPE_OF ┆ EO"]      ┆           ┆   ┆ 00:00:00  ┆           ┆ ITY_OTHER ┆          │
│ f9b…      ┆ _PL…      ┆           ┆           ┆   ┆           ┆           ┆ "]        ┆          │
│ 27ebdca3- ┆ STATEMENT ┆ ["CONTENT ┆ Yes       ┆ … ┆ 2025-01-0 ┆ TikTok    ┆ ["DECISIO ┆ v1       │
│ 085f-47d3 ┆ _CATEGORY ┆ _TYPE_TEX ┆           ┆   ┆ 1         ┆           ┆ N_VISIBIL ┆          │
│ -91ad-79e ┆ _ILLEGAL_ ┆ T"]       ┆           ┆   ┆ 00:00:00  ┆           ┆ ITY_CONTE ┆          │
│ 35b…      ┆ OR_…      ┆           ┆           ┆   ┆           ┆           ┆ NT_…      ┆          │
│ 73aa4ad5- ┆ STATEMENT ┆ ["CONTENT ┆ Yes       ┆ … ┆ 2025-01-0 ┆ TikTok    ┆ ["DECISIO ┆ v1       │
│ 3480-4597 ┆ _CATEGORY ┆ _TYPE_VID ┆           ┆   ┆ 1         ┆           ┆ N_VISIBIL ┆          │
│ -b1aa-c3b ┆ _SCOPE_OF ┆ EO"]      ┆           ┆   ┆ 00:00:00  ┆           ┆ ITY_OTHER ┆          │
│ eb2…      ┆ _PL…      ┆           ┆           ┆   ┆           ┆           ┆ "]        ┆          │
│ f277ba47- ┆ STATEMENT ┆ ["CONTENT ┆ Yes       ┆ … ┆ 2025-01-0 ┆ TikTok    ┆ ["DECISIO ┆ v1       │
│ b2ab-4e97 ┆ _CATEGORY ┆ _TYPE_VID ┆           ┆   ┆ 1         ┆           ┆ N_VISIBIL ┆          │
│ -b5a8-ec7 ┆ _SCOPE_OF ┆ EO"]      ┆           ┆   ┆ 00:00:00  ┆           ┆ ITY_OTHER ┆          │
│ e41…      ┆ _PL…      ┆           ┆           ┆   ┆           ┆           ┆ "]        ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

### X

In [5]:
pl.scan_parquet(str(X_FILE)).head(5).collect()

shape: (5, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ uuid      ┆ category  ┆ content_t ┆ automated ┆ … ┆ applicati ┆ platform_ ┆ decision_ ┆ api_vers │
│ ---       ┆ ---       ┆ ype       ┆ _detectio ┆   ┆ on_date   ┆ name      ┆ visibilit ┆ ion      │
│ str       ┆ str       ┆ ---       ┆ n         ┆   ┆ ---       ┆ ---       ┆ y         ┆ ---      │
│           ┆           ┆ str       ┆ ---       ┆   ┆ datetime[ ┆ str       ┆ ---       ┆ str      │
│           ┆           ┆           ┆ str       ┆   ┆ ms]       ┆           ┆ str       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 457e68f1- ┆ STATEMENT ┆ ["CONTENT ┆ No        ┆ … ┆ 2025-01-0 ┆ X         ┆ ["DECISIO ┆ v1       │
│ ed59-470e ┆ _CATEGORY ┆ _TYPE_SYN ┆           ┆   ┆ 1         ┆           ┆ N_VISIBIL ┆          │
│ -9a6b-990 ┆ _SCAMS_AN ┆ THETIC_ME ┆           ┆   ┆ 00:00:00  ┆           ┆ ITY_OTHER ┆          │
│ 2d2…      ┆ D_F…      ┆ DIA…      ┆           ┆   ┆           ┆           ┆ "]        ┆          │
│ a07aa67e- ┆ STATEMENT ┆ ["CONTENT ┆ No        ┆ … ┆ 2025-01-0 ┆ X         ┆ ["DECISIO ┆ v1       │
│ adbe-4f3e ┆ _CATEGORY ┆ _TYPE_SYN ┆           ┆   ┆ 1         ┆           ┆ N_VISIBIL ┆          │
│ -ab4b-c48 ┆ _SCAMS_AN ┆ THETIC_ME ┆           ┆   ┆ 00:00:00  ┆           ┆ ITY_OTHER ┆          │
│ 5b4…      ┆ D_F…      ┆ DIA…      ┆           ┆   ┆           ┆           ┆ "]        ┆          │
│ 604e6f72- ┆ STATEMENT ┆ ["CONTENT ┆ No        ┆ … ┆ 2025-01-0 ┆ X         ┆ ["DECISIO ┆ v1       │
│ 6a67-43ab ┆ _CATEGORY ┆ _TYPE_SYN ┆           ┆   ┆ 1         ┆           ┆ N_VISIBIL ┆          │
│ -8f77-003 ┆ _SCAMS_AN ┆ THETIC_ME ┆           ┆   ┆ 00:00:00  ┆           ┆ ITY_OTHER ┆          │
│ c66…      ┆ D_F…      ┆ DIA…      ┆           ┆   ┆           ┆           ┆ "]        ┆          │
│ 9487ad6c- ┆ STATEMENT ┆ ["CONTENT ┆ No        ┆ … ┆ 2025-01-0 ┆ X         ┆ ["DECISIO ┆ v1       │
│ e72d-493d ┆ _CATEGORY ┆ _TYPE_SYN ┆           ┆   ┆ 1         ┆           ┆ N_VISIBIL ┆          │
│ -b25f-4f9 ┆ _PORNOGRA ┆ THETIC_ME ┆           ┆   ┆ 00:00:00  ┆           ┆ ITY_OTHER ┆          │
│ 826…      ┆ PHY…      ┆ DIA…      ┆           ┆   ┆           ┆           ┆ "]        ┆          │
│ 3eadd52f- ┆ STATEMENT ┆ ["CONTENT ┆ No        ┆ … ┆ 2025-01-0 ┆ X         ┆ ["DECISIO ┆ v1       │
│ deef-45c9 ┆ _CATEGORY ┆ _TYPE_SYN ┆           ┆   ┆ 1         ┆           ┆ N_VISIBIL ┆          │
│ -9f3d-d41 ┆ _UNSAFE_A ┆ THETIC_ME ┆           ┆   ┆ 00:00:00  ┆           ┆ ITY_OTHER ┆          │
│ 9a2…      ┆ ND_…      ┆ DIA…      ┆           ┆   ┆           ┆           ┆ "]        ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## 6. Key Observations

- **Scale:** TikTok filed roughly 5,400x more SoRs than X for Germany in 2025. This is a central empirical finding of the thesis.
- **Categories:** The `category` field uses different label sets in v1 and v2 submissions. Raw labels are therefore not directly comparable across the two API versions -- see Notebook 03 for the harmonization approach.
- **Territorial scope:** TikTok entries frequently list multiple countries (e.g. `DE,FR,IT`), reflecting EEA-wide enforcement. X entries use single-country codes only, reflecting country-specific enforcement.
- **All columns are categorical or temporal.** There are no numeric measurement columns, so variance is not a meaningful metric for this dataset.