# Notebook 03 -- Category Harmonization

**Thesis:** Content Moderation on TikTok and X -- A Comparative Analysis of DSA Statements of Reasons (2025)  
**Author:** Mohsen Zahedi  

> **Note:** This notebook is pre-run. Data lives at `C:\BA_Data\` and is not included in this repository.

---

This notebook documents the category harmonization step. The core problem is that the DSA API changed its `category` vocabulary on July 1, 2025 (v1 to v2), making direct comparison of records across that boundary impossible without a mapping layer.

In [9]:
from pathlib import Path

import polars as pl

DATA_ROOT = Path(r"C:\BA_Data")
TIKTOK_RAW = DATA_ROOT / "tiktok_de_2025.parquet"
X_RAW = DATA_ROOT / "x_de_2025.parquet"
TIKTOK_HARMONIZED = DATA_ROOT / "tiktok_de_2025_harmonized.parquet"
X_HARMONIZED = DATA_ROOT / "x_de_2025_harmonized.parquet"

# Mapping table is part of the repository
REPO_ROOT = Path("__file__").resolve().parents[1] if "__file__" in dir() else Path(".").resolve().parent
MAPPING_CSV = REPO_ROOT / "03_harmonization" / "taxonomy_mapping_v1_v2.csv"

## 1. The v1/v2 Schema Break

On **July 1, 2025** the DSA Commission released a new submission API (v2) that modified the `category` field:

- Some categories were **renamed** (e.g. `SCOPE_OF_PLATFORM_SERVICE` became `OTHER_VIOLATION_TC`)
- One category was **removed** (`NON_CONSENSUAL_BEHAVIOUR`, no v2 equivalent)
- One category was officially **introduced** in v2 (`CYBER_VIOLENCE`), though it already appeared in some v1 records

[DSA Official change logs](https://transparency.dsa.ec.europa.eu/page/api-documentation#changelog)

Without harmonization, any category-level comparison between the v1 period (Jan--Jun 2025) and the v2 period (Jul--Dec 2025) would be misleading.

In [10]:
# Raw category labels in TikTok, split by api_version
raw_cats = (
    pl.scan_parquet(str(TIKTOK_RAW))
    .group_by(["api_version", "category"])
    .agg(pl.len().alias("count"))
    .sort(["api_version", "count"], descending=[False, True])
    .collect(engine="streaming")
)

print("TikTok raw categories per api_version:")
with pl.Config(fmt_str_lengths=100, tbl_rows=100):
    display(raw_cats)

TikTok raw categories per api_version:

shape: (29, 3)
┌─────────────┬─────────────────────────────────────────────────────────────────────┬───────────┐
│ api_version ┆ category                                                            ┆ count     │
│ ---         ┆ ---                                                                 ┆ ---       │
│ str         ┆ str                                                                 ┆ u32       │
╞═════════════╪═════════════════════════════════════════════════════════════════════╪═══════════╡
│ v1          ┆ STATEMENT_CATEGORY_ILLEGAL_OR_HARMFUL_SPEECH                        ┆ 399152169 │
│ v1          ┆ STATEMENT_CATEGORY_SCOPE_OF_PLATFORM_SERVICE                        ┆ 328623461 │
│ v1          ┆ STATEMENT_CATEGORY_NEGATIVE_EFFECTS_ON_CIVIC_DISCOURSE_OR_ELECTIONS ┆ 37292141  │
│ v1          ┆ STATEMENT_CATEGORY_VIOLENCE                                         ┆ 29874258  │
│ v1          ┆ STATEMENT_CATEGORY_PROTECTION_OF_MINORS                             ┆ 12604612  │
│ v1          ┆ STATEMENT_CATEGORY_SCAMS_AND_FRAUD                                  ┆ 11372842  │
│ v1          ┆ STATEMENT_CATEGORY_PORNOGRAPHY_OR_SEXUALIZED_CONTENT                ┆ 5714374   │
│ v1          ┆ STATEMENT_CATEGORY_DATA_PROTECTION_AND_PRIVACY_VIOLATIONS           ┆ 3616694   │
│ v1          ┆ STATEMENT_CATEGORY_SELF_HARM                                        ┆ 973242    │
│ v1          ┆ STATEMENT_CATEGORY_ANIMAL_WELFARE                                   ┆ 948719    │
│ v1          ┆ STATEMENT_CATEGORY_INTELLECTUAL_PROPERTY_INFRINGEMENTS              ┆ 45491     │
│ v1          ┆ STATEMENT_CATEGORY_NON_CONSENSUAL_BEHAVIOUR                         ┆ 2539      │
│ v1          ┆ STATEMENT_CATEGORY_RISK_FOR_PUBLIC_SECURITY                         ┆ 1348      │
│ v1          ┆ STATEMENT_CATEGORY_UNSAFE_AND_ILLEGAL_PRODUCTS                      ┆ 448       │
│ v2          ┆ STATEMENT_CATEGORY_OTHER_VIOLATION_TC                               ┆ 112661946 │
│ v2          ┆ STATEMENT_CATEGORY_ILLEGAL_OR_HARMFUL_SPEECH                        ┆ 35245452  │
│ v2          ┆ STATEMENT_CATEGORY_NEGATIVE_EFFECTS_ON_CIVIC_DISCOURSE_OR_ELECTIONS ┆ 8247264   │
│ v2          ┆ STATEMENT_CATEGORY_VIOLENCE                                         ┆ 4110146   │
│ v2          ┆ STATEMENT_CATEGORY_PROTECTION_OF_MINORS                             ┆ 3469159   │
│ v2          ┆ STATEMENT_CATEGORY_SCAMS_AND_FRAUD                                  ┆ 2187070   │
│ v2          ┆ STATEMENT_CATEGORY_DATA_PROTECTION_AND_PRIVACY_VIOLATIONS           ┆ 982954    │
│ v2          ┆ STATEMENT_CATEGORY_SELF_HARM                                        ┆ 267071    │
│ v2          ┆ STATEMENT_CATEGORY_ANIMAL_WELFARE                                   ┆ 198251    │
│ v2          ┆ STATEMENT_CATEGORY_INTELLECTUAL_PROPERTY_INFRINGEMENTS              ┆ 94441     │
│ v2          ┆ STATEMENT_CATEGORY_CYBER_VIOLENCE                                   ┆ 1389      │
│ v2          ┆ STATEMENT_CATEGORY_RISK_FOR_PUBLIC_SECURITY                         ┆ 402       │
│ v2          ┆ STATEMENT_CATEGORY_UNSAFE_AND_PROHIBITED_PRODUCTS                   ┆ 358       │
│ v2          ┆ STATEMENT_CATEGORY_SCOPE_OF_PLATFORM_SERVICE                        ┆ 19        │
│ v2          ┆ STATEMENT_CATEGORY_PORNOGRAPHY_OR_SEXUALIZED_CONTENT                ┆ 7         │
└─────────────┴─────────────────────────────────────────────────────────────────────┴───────────┘

In [11]:
# Raw category labels in X, split by api_version
raw_cats_x = (
    pl.scan_parquet(str(X_RAW))
    .group_by(["api_version", "category"])
    .agg(pl.len().alias("count"))
    .sort(["api_version", "count"], descending=[False, True])
    .collect()
)

print("X raw categories per api_version:")
with pl.Config(fmt_str_lengths=100, tbl_rows=100):
    display(raw_cats_x)

X raw categories per api_version:

shape: (28, 3)
┌─────────────┬───────────────────────────────────────────────────────────┬───────┐
│ api_version ┆ category                                                  ┆ count │
│ ---         ┆ ---                                                       ┆ ---   │
│ str         ┆ str                                                       ┆ u32   │
╞═════════════╪═══════════════════════════════════════════════════════════╪═══════╡
│ v1          ┆ STATEMENT_CATEGORY_SCOPE_OF_PLATFORM_SERVICE              ┆ 60974 │
│ v1          ┆ STATEMENT_CATEGORY_PORNOGRAPHY_OR_SEXUALIZED_CONTENT      ┆ 32189 │
│ v1          ┆ STATEMENT_CATEGORY_PROTECTION_OF_MINORS                   ┆ 13643 │
│ v1          ┆ STATEMENT_CATEGORY_SCAMS_AND_FRAUD                        ┆ 8290  │
│ v1          ┆ STATEMENT_CATEGORY_VIOLENCE                               ┆ 6357  │
│ v1          ┆ STATEMENT_CATEGORY_UNSAFE_AND_ILLEGAL_PRODUCTS            ┆ 5146  │
│ v1          ┆ STATEMENT_CATEGORY_NON_CONSENSUAL_BEHAVIOUR               ┆ 2103  │
│ v1          ┆ STATEMENT_CATEGORY_SELF_HARM                              ┆ 2084  │
│ v1          ┆ STATEMENT_CATEGORY_INTELLECTUAL_PROPERTY_INFRINGEMENTS    ┆ 906   │
│ v1          ┆ STATEMENT_CATEGORY_DATA_PROTECTION_AND_PRIVACY_VIOLATIONS ┆ 282   │
│ v1          ┆ STATEMENT_CATEGORY_ILLEGAL_OR_HARMFUL_SPEECH              ┆ 167   │
│ v1          ┆ STATEMENT_CATEGORY_CYBER_VIOLENCE                         ┆ 34    │
│ v1          ┆ STATEMENT_CATEGORY_ANIMAL_WELFARE                         ┆ 10    │
│ v1          ┆ STATEMENT_CATEGORY_RISK_FOR_PUBLIC_SECURITY               ┆ 4     │
│ v1          ┆ STATEMENT_CATEGORY_OTHER_VIOLATION_TC                     ┆ 1     │
│ v1          ┆ STATEMENT_CATEGORY_UNSAFE_AND_PROHIBITED_PRODUCTS         ┆ 1     │
│ v2          ┆ STATEMENT_CATEGORY_CYBER_VIOLENCE                         ┆ 19143 │
│ v2          ┆ STATEMENT_CATEGORY_OTHER_VIOLATION_TC                     ┆ 7265  │
│ v2          ┆ STATEMENT_CATEGORY_PROTECTION_OF_MINORS                   ┆ 7110  │
│ v2          ┆ STATEMENT_CATEGORY_UNSAFE_AND_PROHIBITED_PRODUCTS         ┆ 5734  │
│ v2          ┆ STATEMENT_CATEGORY_SCAMS_AND_FRAUD                        ┆ 4936  │
│ v2          ┆ STATEMENT_CATEGORY_VIOLENCE                               ┆ 4591  │
│ v2          ┆ STATEMENT_CATEGORY_INTELLECTUAL_PROPERTY_INFRINGEMENTS    ┆ 1018  │
│ v2          ┆ STATEMENT_CATEGORY_SELF_HARM                              ┆ 1018  │
│ v2          ┆ STATEMENT_CATEGORY_DATA_PROTECTION_AND_PRIVACY_VIOLATIONS ┆ 185   │
│ v2          ┆ STATEMENT_CATEGORY_ILLEGAL_OR_HARMFUL_SPEECH              ┆ 125   │
│ v2          ┆ STATEMENT_CATEGORY_ANIMAL_WELFARE                         ┆ 3     │
│ v2          ┆ STATEMENT_CATEGORY_RISK_FOR_PUBLIC_SECURITY               ┆ 2     │
└─────────────┴───────────────────────────────────────────────────────────┴───────┘

## 1b. How Many Unique Categories Exist Per Platform?

Before harmonization, both platforms report violations using DSA-defined category labels. The label set changed between v1 (before July 1, 2025) and v2 (from July 1, 2025 onwards). The cell below counts how many distinct category labels each platform actually used in each API version.

In [12]:
for label, df in [("TikTok", raw_cats), ("X", raw_cats_x)]:
    print(f"{label}:")
    summary = (
        df.group_by("api_version")
        .agg(pl.col("category").n_unique().alias("unique_categories"))
        .sort("api_version")
    )
    for row in summary.iter_rows(named=True):
        print(f"  {row['api_version']}: {row['unique_categories']} unique category labels")
    print()

TikTok:
  v1: 14 unique category labels
  v2: 15 unique category labels

X:
  v1: 16 unique category labels
  v2: 12 unique category labels

## 1c. What Changed Between v1 and v2?

Categories that appear **only in v1** were either removed or renamed in v2. Categories **only in v2** are either new or renamed from v1. Categories **in both** were carried over unchanged. This comparison -- done per platform -- shows exactly why a mapping layer is needed before any cross-period analysis.

In [13]:
for label, df in [("TikTok", raw_cats), ("X", raw_cats_x)]:
    v1 = set(df.filter(pl.col("api_version") == "v1")["category"].to_list())
    v2 = set(df.filter(pl.col("api_version") == "v2")["category"].to_list())

    only_v1 = sorted(v1 - v2)
    only_v2 = sorted(v2 - v1)
    in_both = sorted(v1 & v2)

    print(f"{'=' * 65}")
    print(f"  {label}")
    print(f"{'=' * 65}")
    print(f"\n  Only in v1 -- removed or renamed in v2 ({len(only_v1)}):")
    for c in only_v1:
        print(f"    - {c}")
    print(f"\n  Only in v2 -- new or renamed from v1 ({len(only_v2)}):")
    for c in only_v2:
        print(f"    - {c}")
    print(f"\n  In both v1 and v2 -- unchanged ({len(in_both)}):")
    for c in in_both:
        print(f"    - {c}")
    print()

=================================================================
  TikTok
=================================================================

  Only in v1 -- removed or renamed in v2 (2):
    - STATEMENT_CATEGORY_NON_CONSENSUAL_BEHAVIOUR
    - STATEMENT_CATEGORY_UNSAFE_AND_ILLEGAL_PRODUCTS

  Only in v2 -- new or renamed from v1 (3):
    - STATEMENT_CATEGORY_CYBER_VIOLENCE
    - STATEMENT_CATEGORY_OTHER_VIOLATION_TC
    - STATEMENT_CATEGORY_UNSAFE_AND_PROHIBITED_PRODUCTS

  In both v1 and v2 -- unchanged (12):
    - STATEMENT_CATEGORY_ANIMAL_WELFARE
    - STATEMENT_CATEGORY_DATA_PROTECTION_AND_PRIVACY_VIOLATIONS
    - STATEMENT_CATEGORY_ILLEGAL_OR_HARMFUL_SPEECH
    - STATEMENT_CATEGORY_INTELLECTUAL_PROPERTY_INFRINGEMENTS
    - STATEMENT_CATEGORY_NEGATIVE_EFFECTS_ON_CIVIC_DISCOURSE_OR_ELECTIONS
    - STATEMENT_CATEGORY_PORNOGRAPHY_OR_SEXUALIZED_CONTENT
    - STATEMENT_CATEGORY_PROTECTION_OF_MINORS
    - STATEMENT_CATEGORY_RISK_FOR_PUBLIC_SECURITY
    - STATEMENT_CATEGORY_SCAMS_AND_FRAUD
    - STATEMENT_CATEGORY_SCOPE_OF_PLATFORM_SERVICE
    - STATEMENT_CATEGORY_SELF_HARM
    - STATEMENT_CATEGORY_VIOLENCE

=================================================================
  X
=================================================================

  Only in v1 -- removed or renamed in v2 (4):
    - STATEMENT_CATEGORY_NON_CONSENSUAL_BEHAVIOUR
    - STATEMENT_CATEGORY_PORNOGRAPHY_OR_SEXUALIZED_CONTENT
    - STATEMENT_CATEGORY_SCOPE_OF_PLATFORM_SERVICE
    - STATEMENT_CATEGORY_UNSAFE_AND_ILLEGAL_PRODUCTS

  Only in v2 -- new or renamed from v1 (0):

  In both v1 and v2 -- unchanged (12):
    - STATEMENT_CATEGORY_ANIMAL_WELFARE
    - STATEMENT_CATEGORY_CYBER_VIOLENCE
    - STATEMENT_CATEGORY_DATA_PROTECTION_AND_PRIVACY_VIOLATIONS
    - STATEMENT_CATEGORY_ILLEGAL_OR_HARMFUL_SPEECH
    - STATEMENT_CATEGORY_INTELLECTUAL_PROPERTY_INFRINGEMENTS
    - STATEMENT_CATEGORY_OTHER_VIOLATION_TC
    - STATEMENT_CATEGORY_PROTECTION_OF_MINORS
    - STATEMENT_CATEGORY_RISK_FOR_PUBLIC_SECURITY
    - STATEMENT_CATEGORY_SCAMS_AND_FRAUD
    - STATEMENT_CATEGORY_SELF_HARM
    - STATEMENT_CATEGORY_UNSAFE_AND_PROHIBITED_PRODUCTS
    - STATEMENT_CATEGORY_VIOLENCE

## 2. Taxonomy Mapping Table

A mapping table (`03_harmonization/taxonomy_mapping_v1_v2.csv`) was created to assign each raw category label to a **Super-Cluster** -- a stable, version-independent label that works across both v1 and v2 records.

The table was built by:
1. Extracting all unique category labels per api_version from TikTok and X
2. Cross-referencing the official DSA API changelog (July 2025)
3. Assigning each label to a Super-Cluster based on semantic proximity

**Script:** `03_harmonization/scripts/harmonize_categories_polars.py`

In [14]:
mapping = pl.read_csv(str(MAPPING_CSV))

with pl.Config(fmt_str_lengths=100, tbl_rows=100):
    display(mapping)

shape: (17, 6)
┌────────────────┬─────────────┬────────────────┬────────────────┬────────────────┬────────────────┐
│ original_categ ┆ api_version ┆ super_cluster  ┆ mapping_type   ┆ dsa_legal_basi ┆ notes          │
│ ory            ┆ ---         ┆ ---            ┆ ---            ┆ s              ┆ ---            │
│ ---            ┆ str         ┆ str            ┆ str            ┆ ---            ┆ str            │
│ str            ┆             ┆                ┆                ┆ str            ┆                │
╞════════════════╪═════════════╪════════════════╪════════════════╪════════════════╪════════════════╡
│ STATEMENT_CATE ┆ both        ┆ ANIMAL_WELFARE ┆ direct         ┆ DSA Art. 3(h)  ┆ Identical in   │
│ GORY_ANIMAL_WE ┆             ┆                ┆                ┆                ┆ v1 and v2      │
│ LFARE          ┆             ┆                ┆                ┆                ┆                │
│ STATEMENT_CATE ┆ both        ┆ CYBER_VIOLENCE ┆ present_in_bot ┆ DSA Changelog  ┆ Officially new │
│ GORY_CYBER_VIO ┆             ┆                ┆ h              ┆ July 2025      ┆ in v2 but      │
│ LENCE          ┆             ┆                ┆                ┆                ┆ appears in v1  │
│                ┆             ┆                ┆                ┆                ┆ records -      │
│                ┆             ┆                ┆                ┆                ┆ document as    │
│                ┆             ┆                ┆                ┆                ┆ anomaly        │
│ STATEMENT_CATE ┆ both        ┆ PRIVACY_AND_DA ┆ direct         ┆ DSA Art. 3(h)  ┆ Identical in   │
│ GORY_DATA_PROT ┆             ┆ TA             ┆                ┆                ┆ v1 and v2      │
│ ECTION_AND_PRI ┆             ┆                ┆                ┆                ┆                │
│ VACY_VIOLATION ┆             ┆                ┆                ┆                ┆                │
│ S              ┆             ┆                ┆                ┆                ┆                │
│ STATEMENT_CATE ┆ both        ┆ HARMFUL_SPEECH ┆ direct         ┆ DSA Art. 3(h)  ┆ Identical in   │
│ GORY_ILLEGAL_O ┆             ┆                ┆                ┆                ┆ v1 and v2      │
│ R_HARMFUL_SPEE ┆             ┆                ┆                ┆                ┆                │
│ CH             ┆             ┆                ┆                ┆                ┆                │
│ STATEMENT_CATE ┆ both        ┆ INTELLECTUAL_P ┆ direct         ┆ DSA Art. 3(h)  ┆ Identical in   │
│ GORY_INTELLECT ┆             ┆ ROPERTY        ┆                ┆                ┆ v1 and v2      │
│ UAL_PROPERTY_I ┆             ┆                ┆                ┆                ┆                │
│ NFRINGEMENTS   ┆             ┆                ┆                ┆                ┆                │
│ STATEMENT_CATE ┆ both        ┆ CIVIC_AND_ELEC ┆ direct         ┆ DSA Art. 3(h)  ┆ Identical in   │
│ GORY_NEGATIVE_ ┆             ┆ TIONS          ┆                ┆                ┆ v1 and v2      │
│ EFFECTS_ON_CIV ┆             ┆                ┆                ┆                ┆                │
│ IC_DISCOURSE_O ┆             ┆                ┆                ┆                ┆                │
│ R_ELECTIONS    ┆             ┆                ┆                ┆                ┆                │
│ STATEMENT_CATE ┆ both        ┆ OTHER          ┆ renamed_from_v ┆ DSA Changelog  ┆ Maps from v1   │
│ GORY_OTHER_VIO ┆             ┆                ┆ 1              ┆ July 2025      ┆ SCOPE_OF_PLATF │
│ LATION_TC      ┆             ┆                ┆                ┆                ┆ ORM_SERVICE    │
│ STATEMENT_CATE ┆ both        ┆ SEXUAL_CONTENT ┆ direct         ┆ DSA Art. 3(h)  ┆ Appears in     │
│ GORY_PORNOGRAP ┆             ┆                ┆                ┆                ┆ both despite   │
│ HY_OR_SEXUALIZ ┆             ┆                ┆                ┆                ┆ being removed  │
│ ED_CONTENT     ┆             ┆                ┆                ┆                ┆ in official v2 │
│                ┆             ┆                ┆                ┆                ┆ schema         │
│ STATEMENT_CATE ┆ both        ┆ PROTECTION_OF_ ┆ direct         ┆ DSA Art. 3(h)  ┆ Identical in   │
│ GORY_PROTECTIO ┆             ┆ MINORS         ┆                ┆                ┆ v1 and v2      │
│ N_OF_MINORS    ┆             ┆                ┆                ┆                ┆                │
│ STATEMENT_CATE ┆ both        ┆ VIOLENCE       ┆ direct         ┆ DSA Art. 3(h)  ┆ Grouped with   │
│ GORY_RISK_FOR_ ┆             ┆                ┆                ┆                ┆ VIOLENCE per   │
│ PUBLIC_SECURIT ┆             ┆                ┆                ┆                ┆ semantic       │
│ Y              ┆             ┆                ┆                ┆                ┆ proximity      │
│ STATEMENT_CATE ┆ both        ┆ SCAMS_AND_FRAU ┆ direct         ┆ DSA Art. 3(h)  ┆ Identical in   │
│ GORY_SCAMS_AND ┆             ┆ D              ┆                ┆                ┆ v1 and v2      │
│ _FRAUD         ┆             ┆                ┆                ┆                ┆                │
│ STATEMENT_CATE ┆ both        ┆ OTHER          ┆ renamed_to_v2  ┆ DSA Changelog  ┆ Renamed to OTH │
│ GORY_SCOPE_OF_ ┆             ┆                ┆                ┆ July 2025      ┆ ER_VIOLATION_T │
│ PLATFORM_SERVI ┆             ┆                ┆                ┆                ┆ C in v2        │
│ CE             ┆             ┆                ┆                ┆                ┆                │
│ STATEMENT_CATE ┆ both        ┆ SELF_HARM      ┆ direct         ┆ DSA Art. 3(h)  ┆ Identical in   │
│ GORY_SELF_HARM ┆             ┆                ┆                ┆                ┆ v1 and v2      │
│ STATEMENT_CATE ┆ both        ┆ UNSAFE_PRODUCT ┆ renamed_from_v ┆ DSA Changelog  ┆ Maps from v1   │
│ GORY_UNSAFE_AN ┆             ┆ S              ┆ 1              ┆ July 2025      ┆ UNSAFE_AND_ILL │
│ D_PROHIBITED_P ┆             ┆                ┆                ┆                ┆ EGAL_PRODUCTS  │
│ RODUCTS        ┆             ┆                ┆                ┆                ┆                │
│ STATEMENT_CATE ┆ both        ┆ VIOLENCE       ┆ direct         ┆ DSA Art. 3(h)  ┆ Identical in   │
│ GORY_VIOLENCE  ┆             ┆                ┆                ┆                ┆ v1 and v2      │
│ STATEMENT_CATE ┆ v1_only     ┆ SEXUAL_CONTENT ┆ removed_in_v2  ┆ DSA Changelog  ┆ No v2          │
│ GORY_NON_CONSE ┆             ┆                ┆                ┆ July 2025      ┆ equivalent -   │
│ NSUAL_BEHAVIOU ┆             ┆                ┆                ┆                ┆ grouped with   │
│ R              ┆             ┆                ┆                ┆                ┆ SEXUAL_CONTENT │
│                ┆             ┆                ┆                ┆                ┆ by semantic    │
│                ┆             ┆                ┆                ┆                ┆ proximity      │
│ STATEMENT_CATE ┆ v1_only     ┆ UNSAFE_PRODUCT ┆ renamed_in_v2  ┆ DSA Changelog  ┆ Renamed to UNS │
│ GORY_UNSAFE_AN ┆             ┆ S              ┆                ┆ July 2025      ┆ AFE_AND_PROHIB │
│ D_ILLEGAL_PROD ┆             ┆                ┆                ┆                ┆ ITED_PRODUCTS  │
│ UCTS           ┆             ┆                ┆                ┆                ┆ in v2          │
└────────────────┴─────────────┴────────────────┴────────────────┴────────────────┴────────────────┘

## 3. Super-Cluster Taxonomy

13 Super-Clusters were defined. Two mapping decisions required explicit justification:

| Decision | Rationale |
|---|---|
| `RISK_FOR_PUBLIC_SECURITY` grouped into **VIOLENCE** | Both involve physical harm. Semantic proximity justifies merging. |
| `CYBER_VIOLENCE` kept as **separate Super-Cluster** | Represents psychological/reputational harm, distinct from physical violence. Also analytically important as a v2-introduced category with a dramatic rise in X data. |
| `NON_CONSENSUAL_BEHAVIOUR` (v1 only) grouped into **SEXUAL_CONTENT** | No v2 equivalent exists. Closest semantic match is SEXUAL_CONTENT. |

All 13 Super-Clusters:

In [15]:
super_clusters = mapping.select("super_cluster").unique().sort("super_cluster")
for sc in super_clusters.to_series().to_list():
    print(f"  - {sc}")

  - ANIMAL_WELFARE
  - CIVIC_AND_ELECTIONS
  - CYBER_VIOLENCE
  - HARMFUL_SPEECH
  - INTELLECTUAL_PROPERTY
  - OTHER
  - PRIVACY_AND_DATA
  - PROTECTION_OF_MINORS
  - SCAMS_AND_FRAUD
  - SELF_HARM
  - SEXUAL_CONTENT
  - UNSAFE_PRODUCTS
  - VIOLENCE

## 3b. Full Super-Cluster Mapping

The table below shows every original DSA category, the Super-Cluster it belongs to, and the DSA legal basis for the grouping. The `mapping_type` column explains the relationship:

| mapping_type | Meaning |
|---|---|
| `direct` | Label is identical in v1 and v2 |
| `renamed_in_v2` | v1 label was renamed in v2 -- both map to the same Super-Cluster |
| `renamed_from_v1` | v2 label that replaced a v1 label |
| `removed_in_v2` | v1 label with no v2 equivalent -- mapped by semantic proximity |
| `present_in_both` | Category appears in both versions despite being officially scoped to one -- treated as an anomaly (see Section 7) |

In [16]:
sc_breakdown = (
    mapping
    .select(["super_cluster", "original_category", "api_version", "mapping_type", "dsa_legal_basis"])
    .sort(["super_cluster", "api_version", "original_category"])
)
with pl.Config(fmt_str_lengths=120, tbl_rows=50):
    display(sc_breakdown)

shape: (17, 5)
┌──────────────────────┬─────────────────────┬─────────────┬─────────────────┬─────────────────────┐
│ super_cluster        ┆ original_category   ┆ api_version ┆ mapping_type    ┆ dsa_legal_basis     │
│ ---                  ┆ ---                 ┆ ---         ┆ ---             ┆ ---                 │
│ str                  ┆ str                 ┆ str         ┆ str             ┆ str                 │
╞══════════════════════╪═════════════════════╪═════════════╪═════════════════╪═════════════════════╡
│ ANIMAL_WELFARE       ┆ STATEMENT_CATEGORY_ ┆ both        ┆ direct          ┆ DSA Art. 3(h)       │
│                      ┆ ANIMAL_WELFARE      ┆             ┆                 ┆                     │
│ CIVIC_AND_ELECTIONS  ┆ STATEMENT_CATEGORY_ ┆ both        ┆ direct          ┆ DSA Art. 3(h)       │
│                      ┆ NEGATIVE_EFFECTS_ON ┆             ┆                 ┆                     │
│                      ┆ _CIVIC_DISCOURSE_OR ┆             ┆                 ┆                     │
│                      ┆ _ELECTIONS          ┆             ┆                 ┆                     │
│ CYBER_VIOLENCE       ┆ STATEMENT_CATEGORY_ ┆ both        ┆ present_in_both ┆ DSA Changelog July  │
│                      ┆ CYBER_VIOLENCE      ┆             ┆                 ┆ 2025                │
│ HARMFUL_SPEECH       ┆ STATEMENT_CATEGORY_ ┆ both        ┆ direct          ┆ DSA Art. 3(h)       │
│                      ┆ ILLEGAL_OR_HARMFUL_ ┆             ┆                 ┆                     │
│                      ┆ SPEECH              ┆             ┆                 ┆                     │
│ INTELLECTUAL_PROPERT ┆ STATEMENT_CATEGORY_ ┆ both        ┆ direct          ┆ DSA Art. 3(h)       │
│ Y                    ┆ INTELLECTUAL_PROPER ┆             ┆                 ┆                     │
│                      ┆ TY_INFRINGEMENTS    ┆             ┆                 ┆                     │
│ OTHER                ┆ STATEMENT_CATEGORY_ ┆ both        ┆ renamed_from_v1 ┆ DSA Changelog July  │
│                      ┆ OTHER_VIOLATION_TC  ┆             ┆                 ┆ 2025                │
│ OTHER                ┆ STATEMENT_CATEGORY_ ┆ both        ┆ renamed_to_v2   ┆ DSA Changelog July  │
│                      ┆ SCOPE_OF_PLATFORM_S ┆             ┆                 ┆ 2025                │
│                      ┆ ERVICE              ┆             ┆                 ┆                     │
│ PRIVACY_AND_DATA     ┆ STATEMENT_CATEGORY_ ┆ both        ┆ direct          ┆ DSA Art. 3(h)       │
│                      ┆ DATA_PROTECTION_AND ┆             ┆                 ┆                     │
│                      ┆ _PRIVACY_VIOLATIONS ┆             ┆                 ┆                     │
│ PROTECTION_OF_MINORS ┆ STATEMENT_CATEGORY_ ┆ both        ┆ direct          ┆ DSA Art. 3(h)       │
│                      ┆ PROTECTION_OF_MINOR ┆             ┆                 ┆                     │
│                      ┆ S                   ┆             ┆                 ┆                     │
│ SCAMS_AND_FRAUD      ┆ STATEMENT_CATEGORY_ ┆ both        ┆ direct          ┆ DSA Art. 3(h)       │
│                      ┆ SCAMS_AND_FRAUD     ┆             ┆                 ┆                     │
│ SELF_HARM            ┆ STATEMENT_CATEGORY_ ┆ both        ┆ direct          ┆ DSA Art. 3(h)       │
│                      ┆ SELF_HARM           ┆             ┆                 ┆                     │
│ SEXUAL_CONTENT       ┆ STATEMENT_CATEGORY_ ┆ both        ┆ direct          ┆ DSA Art. 3(h)       │
│                      ┆ PORNOGRAPHY_OR_SEXU ┆             ┆                 ┆                     │
│                      ┆ ALIZED_CONTENT      ┆             ┆                 ┆                     │
│ SEXUAL_CONTENT       ┆ STATEMENT_CATEGORY_ ┆ v1_only     ┆ removed_in_v2   ┆ DSA Changelog July  │
│                      ┆ NON_CONSENSUAL_BEHA ┆             ┆                 ┆ 2025                │
│                      ┆ VIOUR               ┆             ┆                 ┆                     │
│ UNSAFE_PRODUCTS      ┆ STATEMENT_CATEGORY_ ┆ both        ┆ renamed_from_v1 ┆ DSA Changelog July  │
│                      ┆ UNSAFE_AND_PROHIBIT ┆             ┆                 ┆ 2025                │
│                      ┆ ED_PRODUCTS         ┆             ┆                 ┆                     │
│ UNSAFE_PRODUCTS      ┆ STATEMENT_CATEGORY_ ┆ v1_only     ┆ renamed_in_v2   ┆ DSA Changelog July  │
│                      ┆ UNSAFE_AND_ILLEGAL_ ┆             ┆                 ┆ 2025                │
│                      ┆ PRODUCTS            ┆             ┆                 ┆                     │
│ VIOLENCE             ┆ STATEMENT_CATEGORY_ ┆ both        ┆ direct          ┆ DSA Art. 3(h)       │
│                      ┆ RISK_FOR_PUBLIC_SEC ┆             ┆                 ┆                     │
│                      ┆ URITY               ┆             ┆                 ┆                     │
│ VIOLENCE             ┆ STATEMENT_CATEGORY_ ┆ both        ┆ direct          ┆ DSA Art. 3(h)       │
│                      ┆ VIOLENCE            ┆             ┆                 ┆                     │
└──────────────────────┴─────────────────────┴─────────────┴─────────────────┴─────────────────────┘

## 3c. Which Original Categories Map to Each Super-Cluster -- Per Platform?

Not all DSA categories appear in both platforms. The table below joins each platform's actual raw category records with the mapping table to show how many records fall under each Super-Cluster per API version. This reveals which Super-Clusters are analytically meaningful for each platform.

In [17]:
for label, df in [("TikTok", raw_cats), ("X", raw_cats_x)]:
    breakdown = (
        df
        .join(
            mapping.select(["original_category", "super_cluster"]),
            left_on="category",
            right_on="original_category",
            how="left"
        )
        .group_by(["super_cluster", "api_version"])
        .agg(pl.col("count").sum().alias("total_records"))
        .sort(["super_cluster", "api_version"])
    )
    print(f"\n{label} -- records per Super-Cluster per api_version:")
    with pl.Config(fmt_str_lengths=60, tbl_rows=50):
        display(breakdown)

TikTok -- records per Super-Cluster per api_version:

shape: (25, 3)
┌───────────────────────┬─────────────┬───────────────┐
│ super_cluster         ┆ api_version ┆ total_records │
│ ---                   ┆ ---         ┆ ---           │
│ str                   ┆ str         ┆ u32           │
╞═══════════════════════╪═════════════╪═══════════════╡
│ ANIMAL_WELFARE        ┆ v1          ┆ 948719        │
│ ANIMAL_WELFARE        ┆ v2          ┆ 198251        │
│ CIVIC_AND_ELECTIONS   ┆ v1          ┆ 37292141      │
│ CIVIC_AND_ELECTIONS   ┆ v2          ┆ 8247264       │
│ CYBER_VIOLENCE        ┆ v2          ┆ 1389          │
│ HARMFUL_SPEECH        ┆ v1          ┆ 399152169     │
│ HARMFUL_SPEECH        ┆ v2          ┆ 35245452      │
│ INTELLECTUAL_PROPERTY ┆ v1          ┆ 45491         │
│ INTELLECTUAL_PROPERTY ┆ v2          ┆ 94441         │
│ OTHER                 ┆ v1          ┆ 328623461     │
│ OTHER                 ┆ v2          ┆ 112661965     │
│ PRIVACY_AND_DATA      ┆ v1          ┆ 3616694       │
│ PRIVACY_AND_DATA      ┆ v2          ┆ 982954        │
│ PROTECTION_OF_MINORS  ┆ v1          ┆ 12604612      │
│ PROTECTION_OF_MINORS  ┆ v2          ┆ 3469159       │
│ SCAMS_AND_FRAUD       ┆ v1          ┆ 11372842      │
│ SCAMS_AND_FRAUD       ┆ v2          ┆ 2187070       │
│ SELF_HARM             ┆ v1          ┆ 973242        │
│ SELF_HARM             ┆ v2          ┆ 267071        │
│ SEXUAL_CONTENT        ┆ v1          ┆ 5716913       │
│ SEXUAL_CONTENT        ┆ v2          ┆ 7             │
│ UNSAFE_PRODUCTS       ┆ v1          ┆ 448           │
│ UNSAFE_PRODUCTS       ┆ v2          ┆ 358           │
│ VIOLENCE              ┆ v1          ┆ 29875606      │
│ VIOLENCE              ┆ v2          ┆ 4110548       │
└───────────────────────┴─────────────┴───────────────┘

X -- records per Super-Cluster per api_version:

shape: (23, 3)
┌───────────────────────┬─────────────┬───────────────┐
│ super_cluster         ┆ api_version ┆ total_records │
│ ---                   ┆ ---         ┆ ---           │
│ str                   ┆ str         ┆ u32           │
╞═══════════════════════╪═════════════╪═══════════════╡
│ ANIMAL_WELFARE        ┆ v1          ┆ 10            │
│ ANIMAL_WELFARE        ┆ v2          ┆ 3             │
│ CYBER_VIOLENCE        ┆ v1          ┆ 34            │
│ CYBER_VIOLENCE        ┆ v2          ┆ 19143         │
│ HARMFUL_SPEECH        ┆ v1          ┆ 167           │
│ HARMFUL_SPEECH        ┆ v2          ┆ 125           │
│ INTELLECTUAL_PROPERTY ┆ v1          ┆ 906           │
│ INTELLECTUAL_PROPERTY ┆ v2          ┆ 1018          │
│ OTHER                 ┆ v1          ┆ 60975         │
│ OTHER                 ┆ v2          ┆ 7265          │
│ PRIVACY_AND_DATA      ┆ v1          ┆ 282           │
│ PRIVACY_AND_DATA      ┆ v2          ┆ 185           │
│ PROTECTION_OF_MINORS  ┆ v1          ┆ 13643         │
│ PROTECTION_OF_MINORS  ┆ v2          ┆ 7110          │
│ SCAMS_AND_FRAUD       ┆ v1          ┆ 8290          │
│ SCAMS_AND_FRAUD       ┆ v2          ┆ 4936          │
│ SELF_HARM             ┆ v1          ┆ 2084          │
│ SELF_HARM             ┆ v2          ┆ 1018          │
│ SEXUAL_CONTENT        ┆ v1          ┆ 34292         │
│ UNSAFE_PRODUCTS       ┆ v1          ┆ 5147          │
│ UNSAFE_PRODUCTS       ┆ v2          ┆ 5734          │
│ VIOLENCE              ┆ v1          ┆ 6361          │
│ VIOLENCE              ┆ v2          ┆ 4593          │
└───────────────────────┴─────────────┴───────────────┘

## 3d. Schema Anomalies

Two categories appeared outside their officially defined API version scope. These are real platform submissions using an unexpected label -- not data errors. Both are documented in the cleaning decisions log (`CD-20260429-02`) and preserved in `category_raw`. The `category_harmonized` column handles them correctly via the mapping table.

| Category | Expected version | Found in | Interpretation |
|---|---|---|---|
| `STATEMENT_CATEGORY_CYBER_VIOLENCE` | v2 only | v1 records | Platforms submitted this label before it was officially introduced |
| `STATEMENT_CATEGORY_PORNOGRAPHY_OR_SEXUALIZED_CONTENT` | v1 only | v2 records | Platforms continued using a removed label after the v2 transition |

In [18]:
anomalies = [
    ("STATEMENT_CATEGORY_CYBER_VIOLENCE", "v1", "officially a v2-only category"),
    ("STATEMENT_CATEGORY_PORNOGRAPHY_OR_SEXUALIZED_CONTENT", "v2", "officially removed in v2"),
]

for label, raw_df in [("TikTok", raw_cats), ("X", raw_cats_x)]:
    print(f"{label}:")
    for category, version, note in anomalies:
        match = raw_df.filter(
            (pl.col("api_version") == version) & (pl.col("category") == category)
        )
        count = match["count"].sum() if len(match) > 0 else 0
        print(f"  {category}")
        print(f"    found in {version} ({note}): {count:,} records")
    print()

TikTok:
  STATEMENT_CATEGORY_CYBER_VIOLENCE
    found in v1 (officially a v2-only category): 0 records
  STATEMENT_CATEGORY_PORNOGRAPHY_OR_SEXUALIZED_CONTENT
    found in v2 (officially removed in v2): 7 records

X:
  STATEMENT_CATEGORY_CYBER_VIOLENCE
    found in v1 (officially a v2-only category): 34 records
  STATEMENT_CATEGORY_PORNOGRAPHY_OR_SEXUALIZED_CONTENT
    found in v2 (officially removed in v2): 0 records

## 4. Before and After Harmonization

The harmonization script added two new columns to each platform's working file:

- `category_harmonized` -- the Super-Cluster label
- `application_date_harmonized` -- date normalized to UTC with the time component removed

The original columns (`category` and `application_date`) were preserved as `category_raw` and `application_date_raw` for audit purposes.

In [19]:
# Show a sample with raw and harmonized columns side by side
(
    pl.scan_parquet(str(TIKTOK_HARMONIZED))
    .select(["api_version", "category_raw", "category_harmonized", "application_date_raw", "application_date_harmonized"])
    .head(8)
    .collect()
)

shape: (8, 5)
┌─────────────┬─────────────────────┬────────────────────┬────────────────────┬────────────────────┐
│ api_version ┆ category_raw        ┆ category_harmonize ┆ application_date_r ┆ application_date_h │
│ ---         ┆ ---                 ┆ d                  ┆ aw                 ┆ armonized          │
│ str         ┆ str                 ┆ ---                ┆ ---                ┆ ---                │
│             ┆                     ┆ str                ┆ date               ┆ date               │
╞═════════════╪═════════════════════╪════════════════════╪════════════════════╪════════════════════╡
│ v1          ┆ STATEMENT_CATEGORY_ ┆ VIOLENCE           ┆ 2025-01-01         ┆ 2025-01-01         │
│             ┆ VIOLENCE            ┆                    ┆                    ┆                    │
│ v1          ┆ STATEMENT_CATEGORY_ ┆ VIOLENCE           ┆ 2025-01-01         ┆ 2025-01-01         │
│             ┆ VIOLENCE            ┆                    ┆                    ┆                    │
│ v1          ┆ STATEMENT_CATEGORY_ ┆ VIOLENCE           ┆ 2025-01-01         ┆ 2025-01-01         │
│             ┆ VIOLENCE            ┆                    ┆                    ┆                    │
│ v1          ┆ STATEMENT_CATEGORY_ ┆ VIOLENCE           ┆ 2025-01-01         ┆ 2025-01-01         │
│             ┆ VIOLENCE            ┆                    ┆                    ┆                    │
│ v1          ┆ STATEMENT_CATEGORY_ ┆ VIOLENCE           ┆ 2025-01-01         ┆ 2025-01-01         │
│             ┆ VIOLENCE            ┆                    ┆                    ┆                    │
│ v1          ┆ STATEMENT_CATEGORY_ ┆ VIOLENCE           ┆ 2025-01-01         ┆ 2025-01-01         │
│             ┆ VIOLENCE            ┆                    ┆                    ┆                    │
│ v1          ┆ STATEMENT_CATEGORY_ ┆ VIOLENCE           ┆ 2025-01-01         ┆ 2025-01-01         │
│             ┆ VIOLENCE            ┆                    ┆                    ┆                    │
│ v1          ┆ STATEMENT_CATEGORY_ ┆ VIOLENCE           ┆ 2025-01-01         ┆ 2025-01-01         │
│             ┆ VIOLENCE            ┆                    ┆                    ┆                    │
└─────────────┴─────────────────────┴────────────────────┴────────────────────┴────────────────────┘

In [20]:
# X -- raw and harmonized columns side by side
(
    pl.scan_parquet(str(X_HARMONIZED))
    .select(["api_version", "category_raw", "category_harmonized", "application_date_raw", "application_date_harmonized"])
    .head(8)
    .collect()
)

shape: (8, 5)
┌─────────────┬─────────────────────┬────────────────────┬────────────────────┬────────────────────┐
│ api_version ┆ category_raw        ┆ category_harmonize ┆ application_date_r ┆ application_date_h │
│ ---         ┆ ---                 ┆ d                  ┆ aw                 ┆ armonized          │
│ str         ┆ str                 ┆ ---                ┆ ---                ┆ ---                │
│             ┆                     ┆ str                ┆ date               ┆ date               │
╞═════════════╪═════════════════════╪════════════════════╪════════════════════╪════════════════════╡
│ v2          ┆ STATEMENT_CATEGORY_ ┆ UNSAFE_PRODUCTS    ┆ 2025-07-06         ┆ 2025-07-06         │
│             ┆ UNSAFE_AND_…        ┆                    ┆                    ┆                    │
│ v2          ┆ STATEMENT_CATEGORY_ ┆ UNSAFE_PRODUCTS    ┆ 2025-07-06         ┆ 2025-07-06         │
│             ┆ UNSAFE_AND_…        ┆                    ┆                    ┆                    │
│ v2          ┆ STATEMENT_CATEGORY_ ┆ UNSAFE_PRODUCTS    ┆ 2025-07-06         ┆ 2025-07-06         │
│             ┆ UNSAFE_AND_…        ┆                    ┆                    ┆                    │
│ v2          ┆ STATEMENT_CATEGORY_ ┆ UNSAFE_PRODUCTS    ┆ 2025-07-06         ┆ 2025-07-06         │
│             ┆ UNSAFE_AND_…        ┆                    ┆                    ┆                    │
│ v2          ┆ STATEMENT_CATEGORY_ ┆ UNSAFE_PRODUCTS    ┆ 2025-07-06         ┆ 2025-07-06         │
│             ┆ UNSAFE_AND_…        ┆                    ┆                    ┆                    │
│ v2          ┆ STATEMENT_CATEGORY_ ┆ SCAMS_AND_FRAUD    ┆ 2025-07-06         ┆ 2025-07-06         │
│             ┆ SCAMS_AND_F…        ┆                    ┆                    ┆                    │
│ v2          ┆ STATEMENT_CATEGORY_ ┆ UNSAFE_PRODUCTS    ┆ 2025-07-06         ┆ 2025-07-06         │
│             ┆ UNSAFE_AND_…        ┆                    ┆                    ┆                    │
│ v2          ┆ STATEMENT_CATEGORY_ ┆ UNSAFE_PRODUCTS    ┆ 2025-07-06         ┆ 2025-07-06         │
│             ┆ UNSAFE_AND_…        ┆                    ┆                    ┆                    │
└─────────────┴─────────────────────┴────────────────────┴────────────────────┴────────────────────┘

## 5. Category Distribution After Harmonization

With categories harmonized, distribution can be compared across v1 and v2 and across platforms.

In [21]:
# TikTok: category distribution per api_version
tiktok_dist = (
    pl.scan_parquet(str(TIKTOK_HARMONIZED))
    .group_by(["api_version", "category_harmonized"])
    .agg(pl.len().alias("count"))
    .sort(["api_version", "count"], descending=[False, True])
    .collect(engine="streaming")
)
print("TikTok -- harmonized category distribution:")
tiktok_dist

TikTok -- harmonized category distribution:

shape: (25, 3)
┌─────────────┬───────────────────────┬───────────┐
│ api_version ┆ category_harmonized   ┆ count     │
│ ---         ┆ ---                   ┆ ---       │
│ str         ┆ str                   ┆ u32       │
╞═════════════╪═══════════════════════╪═══════════╡
│ v1          ┆ HARMFUL_SPEECH        ┆ 399152169 │
│ v1          ┆ OTHER                 ┆ 328623461 │
│ v1          ┆ CIVIC_AND_ELECTIONS   ┆ 37292141  │
│ v1          ┆ VIOLENCE              ┆ 29875606  │
│ v1          ┆ PROTECTION_OF_MINORS  ┆ 12604612  │
│ …           ┆ …                     ┆ …         │
│ v2          ┆ ANIMAL_WELFARE        ┆ 198251    │
│ v2          ┆ INTELLECTUAL_PROPERTY ┆ 94441     │
│ v2          ┆ CYBER_VIOLENCE        ┆ 1389      │
│ v2          ┆ UNSAFE_PRODUCTS       ┆ 358       │
│ v2          ┆ SEXUAL_CONTENT        ┆ 7         │
└─────────────┴───────────────────────┴───────────┘

In [22]:
# X: category distribution per api_version
x_dist = (
    pl.scan_parquet(str(X_HARMONIZED))
    .group_by(["api_version", "category_harmonized"])
    .agg(pl.len().alias("count"))
    .sort(["api_version", "count"], descending=[False, True])
    .collect()
)
print("X -- harmonized category distribution:")
x_dist

X -- harmonized category distribution:

shape: (23, 3)
┌─────────────┬───────────────────────┬───────┐
│ api_version ┆ category_harmonized   ┆ count │
│ ---         ┆ ---                   ┆ ---   │
│ str         ┆ str                   ┆ u32   │
╞═════════════╪═══════════════════════╪═══════╡
│ v1          ┆ OTHER                 ┆ 60975 │
│ v1          ┆ SEXUAL_CONTENT        ┆ 34292 │
│ v1          ┆ PROTECTION_OF_MINORS  ┆ 13643 │
│ v1          ┆ SCAMS_AND_FRAUD       ┆ 8290  │
│ v1          ┆ VIOLENCE              ┆ 6361  │
│ …           ┆ …                     ┆ …     │
│ v2          ┆ INTELLECTUAL_PROPERTY ┆ 1018  │
│ v2          ┆ SELF_HARM             ┆ 1018  │
│ v2          ┆ PRIVACY_AND_DATA      ┆ 185   │
│ v2          ┆ HARMFUL_SPEECH        ┆ 125   │
│ v2          ┆ ANIMAL_WELFARE        ┆ 3     │
└─────────────┴───────────────────────┴───────┘

## 6. Key Findings from Harmonization

- **TikTok dominant category shifted dramatically:** `HARMFUL_SPEECH` dominated v1 (48.05%), but `OTHER` (mapping from `OTHER_VIOLATION_TC`) dominated v2 (67.27%). This reflects a genuine change in TikTok's reporting behavior after the schema transition, not a data artifact.
- **X CYBER_VIOLENCE exploded in v2:** 34 records in v1 vs 19,143 records in v2 (37.44% of all X v2 records). The clearest schema transition effect in the dataset.
- **Zero unmapped categories:** Validation confirmed every raw category label in both platforms was covered by the mapping table.